name: Backend CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    env:
      FLASK_ENV: testing
      MONGO_URI: mongodb://localhost:27017

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install flake8 python-dotenv

      - name: Lint with flake8
        run: |
          flake8 . || echo "flake8 warnings only (pipeline still passes)"

      - name: Run tests
        run: pytest -v --maxfail=1 --disable-warnings
